services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_USER=sa
      - DB_PASSWORD=Kacu938861
      - DB_SERVER=host.docker.internal\ARCHASERVER
      - DB_NAME=WebAppTEST
      - DB_PORT=1433
      - ACCESS_TOKEN_SECRET=cDb!Yu6wU!2

      # Configurazione storage 
      - STORAGE_TYPE=local                    # Cambia a 'remote' per attivare storage remoto
      - LOCAL_STORAGE_PATH=/usr/src/app/uploads
      # - REMOTE_STORAGE_PATH=//192.168.1.100/share
      # - REMOTE_STORAGE_TYPE=mounted         # 'mounted', 'smb', o 'nfs'
      # - SMB_PATH=//192.168.1.100/share/folder
      # - STORAGE_DOMAIN=DOMAIN
      # - STORAGE_USERNAME=username
      # - STORAGE_PASSWORD=password
      
      # ... altre variabili di ambiente ...
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      
      # Volume per storage locale (commenta per storage remoto)
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/temp:/usr/src/app/temp
      
      # Volume per storage remoto (decommentare e modificare per storage remoto)
      # Esempio per NFS:
      # - type: volume
      #   source: remote_uploads
      #   target: /usr/src/app/uploads
      #   volume:
      #     nocopy: true
    
    networks:
      - app-network-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://10.0.0.129:3001/api
    volumes:
      - ./frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge