# Build stage
FROM node:20-alpine as build

WORKDIR /usr/src/app

# Installa pacchetti essenziali
RUN apk add --no-cache git

# Copia package.json e package-lock.json
COPY package*.json ./

# Installa le dipendenze
RUN npm install
RUN npm install @dnd-kit/core @dnd-kit/sortable @dnd-kit/utilities --save

# Copia il resto del codice sorgente
COPY . .

# Correggi il CSS spostando l'importazione Gantt prima di Tailwind
RUN if grep -q "@import \"gantt-task-react/dist/index.css\";" ./src/index.css; then \
    sed -i 's/@import "gantt-task-react\/dist\/index.css";//' ./src/index.css && \
    sed -i '1s/^/@import "gantt-task-react\/dist\/index.css";\n/' ./src/index.css; \
fi

# Build dell'applicazione
RUN npm run build

# Production stage
FROM nginx:alpine

# Crea la directory per i certificati SSL
RUN mkdir -p /etc/nginx/ssl

# IMPORTANTE: Rimuovi la configurazione default di nginx
RUN rm -f /etc/nginx/conf.d/default.conf

# Copia i file buildati nella directory di nginx
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Copia la configurazione di nginx con il nome corretto
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia i certificati SSL direttamente dalla cartella ssl all'interno del contesto di build
COPY ssl/certificato.pem /etc/nginx/ssl/
COPY ssl/chiave.pem /etc/nginx/ssl/

# Esposizione porte HTTP e HTTPS
EXPOSE 80
EXPOSE 443

# Avvio nginx
CMD ["nginx", "-g", "daemon off;"]