-- Fix: Elimina cicli/routing quando si crea un componente manuale con ImportBOM = false
-- CORREZIONE: Il DELETE deve essere eseguito DOPO la chiamata a MA_ProjectArticles_SyncComponent
-- ma PRIMA della logica di importazione BOM, così la BOM del componente esiste già.

USE [WebAppTEST]
GO

PRINT '========================================'
PRINT 'FIX: Elimina cicli quando ImportBOM = false'
PRINT '========================================'
PRINT ''
PRINT 'PROBLEMA:'
PRINT 'Il DELETE dei cicli viene eseguito troppo presto, prima che la BOM del componente'
PRINT 'sia stata creata da MA_ProjectArticles_SyncComponent.'
PRINT ''
PRINT 'SOLUZIONE:'
PRINT 'Spostare il DELETE subito dopo la chiamata a MA_ProjectArticles_SyncComponent'
PRINT '(dopo il controllo errori, riga 5933) e PRIMA della logica di importazione BOM.'
PRINT ''
PRINT '========================================'
PRINT 'ISTRUZIONI PER APPLICARE IL FIX:'
PRINT '========================================'
PRINT '1. Rimuovere il blocco DELETE attuale (dopo riga 6140)'
PRINT '2. Inserire il nuovo blocco DELETE dopo la riga 5933 (dopo il controllo errori di SyncComponent)'
PRINT '3. Il nuovo codice deve essere:'
PRINT ''
PRINT '-- FIX: Elimina cicli/routing se ImportBOM = 0 e componente manuale (non temporaneo)'
PRINT '-- Eseguito DOPO SyncComponent così la BOM del componente esiste già'
PRINT 'IF @Action = ''ADD_COMPONENT'' AND @ImportBOM = 0 AND @CreateTempComponent = 0 AND @RealComponentId IS NOT NULL'
PRINT 'BEGIN'
PRINT '    -- Trova la BOM del componente appena creato/sincronizzato'
PRINT '    DECLARE @ComponentBOMIdToClean BIGINT;'
PRINT '    SELECT TOP 1 @ComponentBOMIdToClean = Id'
PRINT '    FROM dbo.MA_ProjectArticles_BillOfMaterials'
PRINT '    WHERE ItemId = @RealComponentId'
PRINT '        AND CompanyId = @CompanyId'
PRINT '        AND ('
PRINT '            (@ComponentMainRefBOMId IS NOT NULL AND MainRefBOMId = @ComponentMainRefBOMId)'
PRINT '            OR'
PRINT '            (@ComponentMainRefBOMId IS NULL AND Version = 1)'
PRINT '        )'
PRINT '    ORDER BY Version DESC;'
PRINT ''
PRINT '    -- Se esiste una BOM, elimina tutti i cicli/routing'
PRINT '    IF @ComponentBOMIdToClean IS NOT NULL'
PRINT '    BEGIN'
PRINT '        DELETE FROM dbo.MA_ProjectArticles_BOMRouting'
PRINT '        WHERE BOMId = @ComponentBOMIdToClean AND CompanyId = @CompanyId;'
PRINT '        '
PRINT '        PRINT ''Cicli/routing eliminati dalla BOM '' + CAST(@ComponentBOMIdToClean AS VARCHAR(20)) + '' per componente manuale con ImportBOM = false'';'
PRINT '    END'
PRINT 'END'
PRINT ''
PRINT 'POSIZIONE:'
PRINT 'Dopo la riga 5933 (dopo: END -- Fine controllo errori SyncComponent)'
PRINT 'Prima della riga 5935 (prima di: -- Se abbiamo un TargetComponentBOMId specifico...)'
PRINT ''
GO
